services:
  backend:
    # image: python:3.13.4-slim-bullseye
    build:
      context: .
      dockerfile: backend/DockerFile
    ports:
      - 8070:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PORT=8000

    env_file:
      - .env.example

    volumes:
      - ./backend/src:/app

    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: backend/DockerFile
        - action: sync+restart
          path: backend/src
          target: /app

  static_html:
    # image: python:3.13.4-slim-bullseye
    build:
      context: .
      dockerfile: static_html/static.DockerFile
    ports:
      - 6000:8000
      - 2000:8000
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app
