services:
  backend:
    # image: python:3.13.4-slim-bullseye
    build:
      context: .
      dockerfile: backend/DockerFile
    ports:
      - 8070:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PORT=8000
      - POSTGRES_URL=postgresql://postgres:postgres@db_service:5432/postgres
    depends_on:
      - db_service
    env_file:
      - .env

    volumes:
      - ./backend/src:/app

    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: backend/DockerFile
        - action: sync+restart
          path: backend/src
          target: /app
  # Database url: POSTGRES_URL="postgresql://postgres:postgres@localhost:5432/postgres"


  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  # static_html:
  #   # image: python:3.13.4-slim-bullseye
  #   build:
  #     context: .
  #     dockerfile: static_html/static.DockerFile
  #   ports:
  #     - 6000:8000
  #     - 2000:8000
  #   command: python -m http.server 8000
  #   volumes:
  #     - ./static_html/src:/app

volumes:
  managed_database:


